# Generated by Django 3.2 on 2021-04-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('lastCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DonationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('account', models.TextField(verbose_name='Donation Account')),
                ('website', models.CharField(max_length=255, verbose_name='Website')),
                ('image', models.CharField(max_length=255, verbose_name='Image URL')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
